### PR TITLE
replica of fb login page

### PR DESCRIPTION
**Pull request by BinduVerma123**

### CODE REVIEW

**Comment by Tlazypanda** [comment]
@BinduVerma123 Great job! :100: Now can you just put these files under a folder with your name and roll no. and we will be ready to merge :smile:

**Comment by Tlazypanda** [comment]
@BinduVerma123 Do check out other tasks under the issue tab as well :smile:

**Comment by Tlazypanda** [comment]
Hey @BinduVerma123 can you remove the fb and other files since you already have them in the folder ? :smile: Let me know if you run into issues

**Comment by BinduVerma123** [comment]
Ok..I have deleted the rest of the files

**Comment by Tlazypanda** [comment]
@BinduVerma123 Awesome!

**Pull request merged**
